config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/user/auth/facebook'
	resources :products
  root 'products#index'
  resources :carts do
    member do
      post :pay
    end
  end
  resources :products do
    member do
      get :add_to_cart
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
		has_many :cartships
	has_many :products, through: :cartships

	def total_price
		cartships.map { |cartship| cartship.quantity * cartship.product.price }.sum
	end
end

app/models/cartship.rb
class Cartship < ApplicationRecord
	belongs_to :product
	belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	validates :title, presence: true
	validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
		
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

	 
	 def self.new_with_session(params, session)
	   super.tap do |user|
	     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
	       user.email = data["email"] if user.email.blank?
	     end
	   end
	 end

	 def self.from_omniauth(auth)
	   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	     user.email = auth.info.email
	     user.password = Devise.friendly_token[0,20]
	     user.name = auth.info.name   # assuming the user model has a name
	     user.image = auth.info.image # assuming the user model has an image
	   end
	 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :load_cart
	def load_cart
		@@users = User.all
		@cart = Cart.find(session[:cart_id]) if session[:cart_id].present?
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		@cart = Cart.find(params[:id])
	end
	def pay
		@cart = Cart.find(params[:id])
		# Set your secret key: remember to change this to your live secret key in production
		# See your keys here: https://dashboard.stripe.com/account/apikeys
		Stripe.api_key = "sk_test_BslPnG2L9OI0qdPgY30TgFYS"

		# Token is created using Checkout or Elements!
		# Get the payment token ID submitted by the form:
		token = params[:stripeToken]

		charge = Stripe::Charge.create({
		    amount: (@cart.total_price * 100).to_i, # Amount in cent
		    currency: 'usd',
		    description: 'Payment for cart #{@cart.id}',
		    source: token,
		})
		@cart.update(status: "copleted")
		session.delete(:cart_id)
		redirect_to root_path, notice: "The chocolate is on it's way"

	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!,  only: [:show, :edit, :update, :destroy]
    before_action :set_product, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
    @products = Product.all
  end

  def show

  end

  def add_to_cart
    if session[:cart_id].blank?
    cart = Cart.create(status: "pending")
    session[:cart_id] = cart.id
    else
      cart = Cart.find(session[:cart_id])
    end
    product = Product.find(params[:id])
    cart.cartships.create(product_id: product.id, quantity: 1)
    redirect_to cart
  end
  def new
    @product = Product.new
    
  end
  def edit
    
  end

  def create
    @product = Product.create(product_params )
    if @product.errors.empty?
      redirect_to product_path(@product)
    else
    render "new"  
    end
  end

  def update
    @product.update_attributes(product_params)
    if @product.errors.empty?
      redirect_to product_path(@product)
    else
    render "edit" 
    end
  end

  def destroy
  end

private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :descption, :price, :image)  
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.haml
%table.table
	%tr
		%th Product Name
		%th Quantity
		%th Price
		%th Total
	- @cart.cartships.each do |cartship|
		%tr
			%td= cartship.product.title
			%td= cartship.quantity
			%td= number_to_currency(cartship.product.price)
			%td= number_to_currency(cartship.product.price * cartship.quantity)
	%tr
		%td{colspan: 3} Total
		%td= number_to_currency(@cart.total_price)
.pull-right
	= form_tag pay_cart_path(@cart), method: :post do
		%script{src: "https://checkout.stripe.com/checkout.js", class: "stripe-button", 
			data: {key: "pk_test_Id3aEnYgAsMk0FyMoXdS256e", amount: @cart.total_price * 100, 
			name: "BIRUANG", description: "BIRUANG Order", image: image_path("slide1.jpg"), 
			locale: "auto"}}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Part3rails2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="unslider.css">
    <link rel="stylesheet" href="unslider-dots.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed' rel='stylesheet' type='text/css'>

  </head>

  <body>
    <%= render 'shared/header' %>
        
      <%= yield %>
    
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/index.html.erb
<div class="chat" data-behavior="vue">
    <% @users.each do |u| %>
      <% if (u.image == nil) %>
        <%= u.name %>
      <% else %>
        <%= image_tag(u.image) %><br />
        <%= u.name %><hr>
      <% end %>  

    <% end %>
  <app></app>  

</div> 

<div class="my-slider center-block-main">
	<ul>
        <li>
            <h2>RIGHT IS PINK. <br>LEFT IS BLUE</h2>
            <p>Inspired by Brasil’s bold colors and matching up to football’s on-pitch<br>
            playmakers, these kicks are ready to stand out.</p>
            <%= image_tag(image_path("slide1.jpg")) %>
        </li>

		<li>
        	<h2>RIGHT IS PINK. <br>LEFT IS BLUE</h2>
            <p>Inspired by Brasil’s bold colors and matching up to football’s on-pitch<br>
			playmakers, these kicks are ready to stand out.</p>

            <%= image_tag(image_path('slide2.jpg'))%>
        </li>
        <li>
        	<h2>RIGHT IS PINK. <br>LEFT IS BLUE</h2>
            <p>Inspired by Brasil’s bold colors and matching up to football’s on-pitch<br>
			playmakers, these kicks are ready to stand out.</p>

            <%= image_tag(image_path('slide3.jpg'))%>
        </li>
	</ul>
</div>

<div class="block3-main center-block-main clearfix">
	<article>
		<%= image_tag(image_path('img31.jpg') )%>
        <h2><a href="#">FOOTBALL SHOES</a></h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing,
vivamus congue nulla leo, quis imperdiet magna.</p>
    </article>
    <article>
    	<%= image_tag(image_path('img32.jpg') )%>
        <h2><a href="#">MODERN CLOTHES</a></h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing,
vivamus congue nulla leo, quis imperdiet magna.</p>
    </article>
    <article>
    	<%= image_tag(image_path('img33.jpg') )%>
        <h2><a href="rafik">BAGS & ACCESSORIES</a></h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing,
vivamus congue nulla leo, quis imperdiet magna.</p>
    </article>
</div>

<section class="block4-section center-block-main">
	<h2>POPULAR PRODUCTS</h2>
    <div class="block4-main clearfix">
    	<% @products.each do |i| %>

		    	<article>
		    		<%= image_tag(i.image.url) %>

		            <div class="block4-main-content">
		            	<h2><%= i.title %></h2>
		                <h3>Running Tank Top</h3>
		                <p><%= i.descption %></p>

						<p class="price-basket clearfix">
		                	<span class="price"><%= number_to_currency(i.price) %> </span>
		                    <span class="basket-btn"><%= link_to image_tag(image_path('ico-plus.jpg')), add_to_cart_product_path(i)   %></span>
		                </p>
		            </div>
		        </article>
			<% end %>
        
    </div>
</section>

<div class="about center-block-main clearfix">
	<article>
    	<h2>About</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dictum lectus sit amet varius pulvinar. Proin vitae 
dui tincidunt nibh facilisis pellentesque.  Fusce tortor turpis, facilisis ut condimentum eu, sagittis at est.</p>

<p>Praesent egestas posuere urna a egestas. Maecenas facilisis orci vitae ante  tempor accumsan. Aenean aliquam 
justo ac sagittis vehicula. Nam mattis pretium odio sit amet vulputate.</p>

<p>Quisque non lobortis orci. Morbi augue mauris, ultrices at fermentum ac, consequat vitae magna. Pellentesque 
non cursus mi, eu cursus nunc. Nullam  et odio tristique, volutpat urna vitae, dignissim orci. Fusce eu nulla urna.
This template was created by Erik Padamans.</p>

<p>Praesent egestas posuere urna a egestas. Maecenas facilisis orci vitae ante  tempor accumsan. Aenean aliquam 
justo ac sagittis vehicula. Nam mattis pretium odio sit amet vulputate.</p>
 
    </article>
    <div class="map">
    	<div class="mapin">
    		<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2795.8964773381153!2d27.56055224704729!3d53.895148625930446!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x0903c79016f027b8!2z0KHRgtCw0LTQuNC-0L0g0JTQuNC90LDQvNC-!5e0!3m2!1sru!2sby!4v1454671639607" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
</div>

<div class="subscribe">
	<div class="center-block-main clearfix">
    	<h2><strong>Sign up</strong> for exclusive sales and product news</h2>
        
        <div class="subscribe-form">
        	<form action="" method="get">
            	<input type="email" class="email-inpt" placeholder="eony321v@gmail.com">
                <input type="submit" class="submit-inpt" value="sign up"
            </form>
        </div>
    </div>
</div>

app/views/products/new.html.erb
<%= form_for @product, html: {multipart: true} do |f| %>
  <p>Изображение: <br/><%= f.file_field :image %></p>
	<p>Цена: <br/><%= f.text_field :price %></p>
	<p>Название:<br/><%= f.text_field :title %></p>
	<p>Описание:<br/><%= f.text_field :descption %></p>
	

	<p><%= f.submit "Создать товар"  %></p>
<% end %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/shared/_footer.html.erb
<footer class="ftr">
	<div class="block4-main center-block-main clearfix">
    	<article>
        	<h2>Our Stores</h2>
            <div class="ftr-block-content">
            	<p>Feel free to visit our stores or contact us.
                1401 South Grand Avenue 
                Los Angeles, CA 90015 
                (213) 748-2411</p>
                
                <p>100 Fairview Drive 
                Franklin, VA 23851 
                (757) 569-6100 </p>
            </div>
        </article>
        <article>
        	<h2>Blog posts</h2>
            <div class="ftr-block-content">
            	<h3><a href="#">Justin Bieber confirmed that he is gay.</a></h3>
                <p>Lorem ipsum dolor sit amet, consectetur
adipiscing elit. Donec sed auctor elit.</p>
				
                <h3><a href="#">Justin Bieber confirmed that he is gay.</a></h3>
                <p>Lorem ipsum dolor sit amet, consectetur
adipiscing elit. Donec sed auctor elit.</p>
            </div>
        </article>
        <article>
        	<h2>Support</h2>
            <div class="ftr-block-content">
            	<p class="support">
                    <a href="#">Terms & Conditions</a>
                    <a href="#">FAQ</a>
                    <a href="#">Payment</a>
                    <a href="#">Refunds</a>
                    <a href="#">Track Order</a>
				</p>
                <p class="support">
                    <a href="#">Services</a>
                    <a href="#">Privacy & Security</a>
                    <a href="#">Careers</a>
                    <a href="#">Press</a>
                </p>
            </div>
        </article>
        <article>
        	<h2>Contact us</h2>
            <div class="ftr-block-content">
            	<form>
                	<input class="ftrmail" type="email" placeholder="your e-mail...">
                    <textarea class="ftrtext" placeholder="your text..."></textarea>
                    <input class="ftrsubmit" type="submit" value="Send MESSAGE">
                </form>
            </div>
        </article>
    </div>
</footer>
<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="unslider-min.js"></script>
<script>
		jQuery(document).ready(function($) {
			$('.my-slider').unslider({
				autoplay:true,
				arrows:false
			});
		});
</script>

<script>
	function setEqualHeight(columns) { 
		var tallestcolumn = 0; 
		columns.each( function() { 
			currentHeight = $(this).height(); 
			if(currentHeight > tallestcolumn) { tallestcolumn = currentHeight; } } ); 
			columns.height(tallestcolumn); 
		} 
		
		$(document).ready(function() { setEqualHeight($(".block4-main-content")); });
</script>

app/views/shared/_header.html.erb
<header>
	<div class="center-block-main">
    	<div class="header-top clearfix">
        	<p class="logo">BIRUANG</p>
            <div class="contakt-basket">
                <% unless current_user %>
                    <p class="sotials">
                        Login with:
                        <%= link_to image_tag(image_path('facebook-icon.png')), user_facebook_omniauth_authorize_path %>
                    </p>
                <% else %>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                <% end %>

                <p class="header-phone">
                    <%= image_tag(image_path('ico-phone.jpg')) %> +371 282 20 760
                </p>
                <p class="header-basket">
                    <%= image_tag(image_path('ico-basket.jpg')) %>  
                    <%-  if @cart.present? %>
                        <%= number_to_currency(@cart.total_price) %>
                    <% end %> 
                    <%= link_to "Checkout", @cart, class: "btn btn-info" %>
                    

                </p>
            </div>
        </div>
        <div class="header-bottom clearfix">
        	<nav>
            	<ul class="menu">
                	<li><a href="">Home</a></li>
                    <li><a href="">MEN</a></li>
                    <li><a href="">WOMEN</a></li>
                    <li><a href="">KIDS</a></li>
                    <li><a href="">SALE</a></li>
                    <li><a href="">ABOUT US</a></li>
                    <li><a href="">SUPPORT</a></li>
                </ul>
            </nav>
            <div class="search-block">
            	<form action="" method="get">
                    <input class="search-btn" type="image" <%= image_tag(image_path('search-btn.jpg')) %>
                    <input type="search" class="search" placeholder="Search...">
                </form>
            </div>
        </div>
    </div>
</header>